lbImpl/src/org/LexGrid/LexBIG/Impl/CodedNodeSetImpl.java, lbImpl/src/org/LexGrid/LexBIG/Impl/codedNodeSetOperations/RestrictToMatchingDesignations.java, lbImpl/src/org/LexGrid/LexBIG/Impl/codedNodeSetOperations/RestrictToMatchingProperties.java, lbImpl/src/org/LexGrid/LexBIG/Impl/codedNodeSetOperations/RestrictToProperties.java, lbImpl/src/org/LexGrid/LexBIG/Impl/dataAccess/RestrictionImplementations.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/CodedNodeSetSerializationTest.java
Fixes to replace the Lucene-based CodedNodeSetImpl query builder with a LexEVS Restriction based one.
=> CodedNodeSetImpl Serialization changes.

lbImpl/src/org/LexGrid/LexBIG/Impl/CodedNodeSetImpl.java, lbImpl/src/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/mapping/CodedNodeSetBackedMapping.java, lbImpl/src/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/mapping/MappingResolvedConceptReferenceIterator.java, lbImpl/src/org/LexGrid/LexBIG/Impl/codedNodeSetOperations/RestrictToMatchingDesignations.java, lbImpl/src/org/LexGrid/LexBIG/Impl/codedNodeSetOperations/RestrictToMatchingProperties.java, lbImpl/src/org/LexGrid/LexBIG/Impl/codedNodeSetOperations/RestrictToProperties.java, lbImpl/src/org/LexGrid/LexBIG/Impl/dataAccess/RestrictionImplementations.java, lbImpl/src/org/LexGrid/LexBIG/Impl/helpers/IteratorBackedResolvedConceptReferencesIterator.java, lbImpl/test/java/org/LexGrid/LexBIG/test/ContentLoadingTestListener.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/CodedNodeSetSerializationTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/MappingExtensionSerializationTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java, lexevs-dao/src/main/java/org/lexevs/dao/index/indexregistry/IndexRegistry.java, lexevs-dao/src/main/java/org/lexevs/dao/index/indexregistry/MultiIndexRegistry.java, lexevs-dao/src/main/java/org/lexevs/dao/index/service/entity/LuceneEntityIndexService.java, lexevs-dao/src/test/java/org/lexevs/dao/test/InMemoryLuceneDirectoryCreator.java
Fix for issue LEXEVS-1801 to ensure that on index drop index registries are properly updated.
=> Fix for issue LEXEVS-1801 to ensure that on index drop index registries are properly updated.

lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/LoadTestDataTest.java
For issue LEXEVS-1848, add the @Test annotations to the new JUnit 4 style tests.
=> For issue LEXEVS-1848, add the @Test annotations to the new JUnit 4 style tests.

lbPackager/build.properties
Pull request to increment the lexevs build to 6.4.1.FINAL.
=> Updating build to 6.4.1.FINAL

loader-framework-core/src/main/java/org/lexgrid/loader/reader/CompositeGroupItemReader.java
Adjusted getters and setters for CompositeGroupItemReader.java
=> bugfix/LEXEVS-2256: Edited for getters and setters

lbPackager/ivysettings.xml
LEXEVS-2329 Updated ivysettings.xml to pull artifacts from NCI's Nexus server instead of informatics
=> LEXEVS-2329 Updated ivysettings.xml to pull artifacts from NCI's Nexus server instead of informatics

lbPackager/ivysettings.xml
LEXEVS-2381 Updated ivy settings to pull artifacts from NCI' Nexus server.
=> LEXEVS-2381 Updated ivy settings to pull artifacts from NCI' Nexus server.

lbPackager/common-build.xml, lbPackager/files/izpack-lexbig.xml, loader-framework-core/src/main/java/org/lexgrid/loader/reader/CompositeGroupItemReader.java
LEXEVS-2398 Updated code to run in Java 1.8.  Updated java targets to Java 1.8
=> LEXEVS-2398 Updated code to run in Java 1.8.  Updated java targets to Java 1.8

lbPackager/build.properties
LEXEVS-2362 Updated build properties to 6.4.2.SNAPSHOT
=> LEXEVS-2362 Updated build properties to 6.4.2.SNAPSHOT

lbPackager/build.properties
LEXEVS-2434  Updates lexevs version to 6.4.1.2.FINAL.
=> LEXEVS-2434  Updates lexevs version to 6.4.1.2.FINAL.

lbGUI/src/org/LexGrid/LexBIG/gui/LB_GUI.java, lbGUI/src/org/LexGrid/LexBIG/gui/codeSystemView/CodeSystemContentProvider.java, lbGUI/src/org/LexGrid/LexBIG/gui/codeSystemView/CodeSystemLabelProvider.java
Bugfix/lexevs 2288 Added ability to sort coding scheme table columns
=> Bugfix/lexevs 2288 Added ability to sort coding scheme table columns

lbGUI/src/org/LexGrid/LexBIG/gui/LB_GUI.java
LEXEVS-2459 Sorted items under the "Load Terminology" menu item alphabetically
=> LEXEVS-2459 Sorted items under the "Load Terminology" alphabetically

lbGUI/src/org/LexGrid/LexBIG/gui/LB_GUI.java, lbGUI/src/org/LexGrid/LexBIG/gui/codeSystemView/CodeSystemContentProvider.java, lbGUI/src/org/LexGrid/LexBIG/gui/codeSystemView/CodeSystemLabelProvider.java
LEXEVS-2288 Merging LBGUI column sorting to v6.4.2
=> LEXEVS-2288 Merging LBGUI column sorting to v6.4.2

lbGUI/src/org/LexGrid/LexBIG/gui/LB_GUI.java
pushing LEXEVS-2489 to 6.4.2 branch.
=> LEXEVS-2489 pushing sorting of Load Terminology menu item to v6.4.2 branch

lbGUI/src/org/LexGrid/LexBIG/gui/load/LoaderExtensionShell.java
LEXEVS-2461 Added a 3 second delay before enabling the "Next Load" button.
=> LEXEVS-2461 Added a 3 second delay before enabling the "Next Load" button.

lbAdmin/src/org/LexGrid/LexBIG/admin/ListSchemes.java
LEXEVS-2529 Updated column widths for displaying coding scheme information
=> LEXEVS-2529 Updated column widths for displaying coding scheme information

lbModel/build.xml, lbPackager/build.xml, lbPackager/common-build.xml, lbPackager/ivysettings.xml, lgModel/build.xml
LEXEVS-2628 Updated ant and ivy scripts to publish artifacts to the NCI Nexus server.
=> LEXEVS-2628 Updated ant and ivy scripts to publish artifacts to the NCI Nexus server.

lbImpl/src/org/LexGrid/LexBIG/Impl/loaders/BaseLoader.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/LoadTestDataTest.java, umls-loader/src/main/java/org/lexgrid/loader/umls/UmlsBatchLoaderImpl.java, umls-loader/src/main/java/org/lexgrid/loader/umls/UmlsBatchLoaderSabVerifier.java
Bugfix/lexevs-1626 Verify the RRF file SAB are valid before performing a UMLS load.
=> Bugfix/lexevs-1626 Verify the RRF file SAB are valid before performing a load

lbGUI/src/org/LexGrid/LexBIG/gui/codeSystemView/CodeSystemLabelProvider.java, lbImpl/src/org/LexGrid/LexBIG/Impl/dataAccess/RestrictionImplementations.java, lbImpl/src/org/LexGrid/LexBIG/Impl/helpers/ResolvedConceptReferencesIteratorImpl.java, lbInterfaces/src/org/LexGrid/LexBIG/Extensions/Generic/CodingSchemeReference.java, lbPackager/build.properties, lbPackager/common-build.xml, lbPackager/files/izpack-lexbig.xml, lbPackager/ivysettings.xml, lbTest/resources/testData/owl2/OWLPrefsLoadAnonAsAssocPF2SetTopNodesByNameToCode.XML, lbTest/resources/testData/owl2/owl2-special-cases-byName-Defined-Annotated2.owl, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/OWL2SpecialCaseSnippetTestIT.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/MappingExtensionImplTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/function/query/ValidateHashCode.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/load/meta/GenericPropertyQueryBySourceOnlyTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/load/meta/GenericPropertyQueryBySourceQualifierTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/LoadTestDataTest.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java, loader-framework-core/src/main/java/org/lexgrid/loader/reader/CompositeGroupItemReader.java
LEXEVS-2717 Merge Java 8 changes to dev branch.
=> LEXEVS-2717 Merge Java 8 changes to dev branch.

lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OWL2UnitTests.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java
LEXEVS-2723 Update OWL2 property check for Java 8
=> LEXEVS-2723 Update OWL2 property check for Java 8

lbPackager/build.properties
LEXEVS-2731 Updated version to 6.4.1.3.FINAL
=> LEXEVS-2731 Updated version to 6.4.1.3.FINAL

lbPackager/build.properties
LEXEVS-2740 Updated build version to 6.5.0.SNAPSHOT.1
=> LEXEVS-2740 Updated build version to 6.5.0.SNAPSHOT.1

lbPackager/build.properties
LEXEVS-2776 - Updated lexevs version to 6.4.1.3.1.RC
=> LEXEVS-2776 - Updated lexevs version to 6.4.1.3.1.RC

lbAdmin/scripts/Load.sh, lbAdmin/scripts/LoadAllDefinitionsToResolvedValueSet.sh, lbAdmin/scripts/LoadAllValueSetDefinitionsInDirectory.sh, lbAdmin/scripts/LoadLgXML.sh, lbAdmin/scripts/LoadMIFVocabulary.sh, lbAdmin/scripts/LoadManifest.sh, lbAdmin/scripts/LoadMedDRA.sh, lbAdmin/scripts/LoadMetaBatch.sh, lbAdmin/scripts/LoadMetadata.sh, lbAdmin/scripts/LoadMrMap.sh, lbAdmin/scripts/LoadNCIHistory.sh, lbAdmin/scripts/LoadOBO.sh, lbAdmin/scripts/LoadUMLSHistory.sh, lbAdmin/scripts/LoadUMLSSemnet.sh, lbAdmin/scripts/LoadUmlsBatch.sh, lbAdmin/scripts/LoadValueSetDefinition.sh
LEXEVS-285 Updated shell scripts with the headless parameter -Djava.awt.headless=true
=> LEXEVS-285 Updated shell scripts with the headless parameter -Djava.awt.headless=true

lbAdmin/scripts/Load.sh, lbAdmin/scripts/LoadAllDefinitionsToResolvedValueSet.sh, lbAdmin/scripts/LoadAllValueSetDefinitionsInDirectory.sh, lbAdmin/scripts/LoadLgXML.sh, lbAdmin/scripts/LoadMIFVocabulary.sh, lbAdmin/scripts/LoadManifest.sh, lbAdmin/scripts/LoadMedDRA.sh, lbAdmin/scripts/LoadMetaBatch.sh, lbAdmin/scripts/LoadMetadata.sh, lbAdmin/scripts/LoadMrMap.sh, lbAdmin/scripts/LoadNCIHistory.sh, lbAdmin/scripts/LoadOBO.sh, lbAdmin/scripts/LoadUMLSHistory.sh, lbAdmin/scripts/LoadUMLSSemnet.sh, lbAdmin/scripts/LoadUmlsBatch.sh, lbAdmin/scripts/LoadValueSetDefinition.sh, lbTest/resources/testData/owl2/OWLPrefsLoadAnonAsAssocPF2SetTopNodes.XML, lbTest/resources/testData/owl2/catalog-v001.xml, lbTest/resources/testData/owl2/owl2-special-cases-Defined-Annotated.owl, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/NewOWL2SnippetTestIT.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/OWL2PrimitivesSnippetTestIT.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/OWL2SpecialCaseSnippetTestIT.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java
Bugfix/lexevs 2778 Merging v6.4.0 branch changes to dev branch
=> Bugfix/lexevs 2778 Merging v6.4.0 branch changes to dev branch

lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java
Bugfix/lexevs 2771 Added a cache of the AnyUIRDataType for better performance (Dev branch)
=> Bugfix/lexevs 2771 Added a cache of the AnyUIRDataType for better performance (Dev branch)

lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java
Bugfix/lexevs 2771 Added a cache of the AnyUIRDataType for better performance
=> Bugfix/lexevs 2771 Added a cache of the AnyUIRDataType for better performance

lbImpl/src/org/LexGrid/LexBIG/Impl/loaders/BaseLoader.java, lbPackager/resources/lbPackager build.xml [build-lexbig].launch, lbTest/resources/testData/owl2/catalog-v001.xml, lbTest/resources/testData/owl2/owl2-special-cases-Defined-Annotated.owl, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/NewOWL2SnippetTestIT.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/OWL2SpecialCaseSnippetTestIT.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/AssociationWrapper.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java
6.5.sprint.52 - Merging sprint 52 issues to the 6.5 Branch
=> 6.5.sprint.52 - Merging sprint 52 issues to the 6.5 Branch

lbImpl/src/org/LexGrid/LexBIG/Impl/loaders/BaseLoader.java, lbPackager/resources/lbPackager build.xml [build-lexbig].launch, lbTest/resources/testData/owl2/catalog-v001.xml, lbTest/resources/testData/owl2/owl2-special-cases-Defined-Annotated.owl, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/NewOWL2SnippetTestIT.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/OWL2SpecialCaseSnippetTestIT.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/AssociationWrapper.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java
Dev.sprint.52 Merging sprint 52 issues to the Dev Branch
=> Dev.sprint.52 Merging sprint 52 issues to the Dev Branch

lbPackager/build.properties
LEXEVS-2867 - Updated version to 6.4.1.4.FINAL
=> LEXEVS-2867 - Updated version to 6.4.1.4.FINAL

lbAdmin/scripts/RemoveResolvedValueSet.bat, lbAdmin/scripts/RemoveResolvedValueSet.sh, lbAdmin/scripts/RemoveVSResolvedFromCodingScheme.bat, lbAdmin/scripts/RemoveVSResolvedFromCodingScheme.sh, lbTest/src/test/java/org/LexGrid/valueset/impl/LexEVSResolvedValueSetTest.java, lbTest/src/test/java/org/LexGrid/valueset/impl/LexEVSValueSetDefServicesImplTest.java, lbTest/src/test/java/org/LexGrid/valueset/test/CleanUpTest.java, lgValueSets/src/org/lexgrid/resolvedvalueset/impl/LexEVSResolvedValueSetServiceImpl.java, lgValueSets/src/org/lexgrid/valuesets/admin/RemoveVSResolvedFromCodingSchemes.java, lgValueSets/src/org/lexgrid/valuesets/helper/VSDServiceHelper.java
6.5.sprint.53 merge LEXEVS-2892 from 6.4.0 branch to 6.5.0 branch
=> 6.5.sprint.53 merge LEXEVS-2892 from 6.4.0 branch to 6.5.0 branch

lbPackager/build.properties
LEXEVS-2874 Updated version to 6.5.0.RC.1
=> LEXEVS-2874 Updated version to 6.5.0.RC.1

lbAdmin/scripts/RemoveResolvedValueSet.bat, lbAdmin/scripts/RemoveResolvedValueSet.sh, lbAdmin/scripts/RemoveVSResolvedFromCodingScheme.bat, lbAdmin/scripts/RemoveVSResolvedFromCodingScheme.sh, lbImpl/src/org/LexGrid/LexBIG/Impl/helpers/lazyloading/AbstractLazyLoadableCodeToReturn.java, lbImpl/src/org/LexGrid/LexBIG/Impl/loaders/BaseLoader.java, lbImpl/src/org/LexGrid/LexBIG/Impl/namespace/DefaultNamespaceHandler.java, lbPackager/build.properties, lbPackager/resources/lbPackager build.xml [build-lexbig].launch, lbTest/resources/testData/owl2/catalog-v001.xml, lbTest/resources/testData/owl2/owl2-special-cases-Defined-Annotated.owl, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/NewOWL2SnippetTestIT.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/OWL2SpecialCaseSnippetTestIT.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/Extensions/tree/test/LexEvsTreeTestBase.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/function/codednodeset/ResolveTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/helpers/lazyloading/LazyLoadableCodeToReturnTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/namespace/DefaultNamespaceHandlerTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java, lbTest/src/test/java/org/LexGrid/valueset/impl/LexEVSResolvedValueSetTest.java, lbTest/src/test/java/org/LexGrid/valueset/impl/LexEVSValueSetDefServicesImplTest.java, lbTest/src/test/java/org/LexGrid/valueset/test/CleanUpTest.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/AssociationWrapper.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java, lgValueSets/src/org/lexgrid/resolvedvalueset/impl/LexEVSResolvedValueSetServiceImpl.java, lgValueSets/src/org/lexgrid/valuesets/admin/RemoveVSResolvedFromCodingSchemes.java, lgValueSets/src/org/lexgrid/valuesets/helper/VSDServiceHelper.java
Bugfix/lexevs 2924 Merge v6.5.0 branch to master for lexevs 6.5.0 release
=> Bugfix/lexevs 2924 Merge v6.5.0 branch to master for lexevs 6.5.0 release

lbPackager/build.properties
LEXEVS-2954 Updated the version to 6.5.0.FINAL
=> LEXEVS-2954 Updated the version to 6.5.0.FINAL

lbPackager/build.properties
LEXEVS-3046 Updated version to 6.5.0.1.RC.1
=> LEXEVS-3046 Updated version to 6.5.0.1.RC.1

lbPackager/build.properties, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/NewOWL2SnippetTestIT.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OWL2UnitTests.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java
Bugfix/lexevs 3015 Merging v6.5.0 branch to dev branch.
This updates the dev branch with the latest 6.5.0.1.FINAL changes
=> Bugfix/lexevs 3015 Merging v6.5.0 branch to dev branch.

lbPackager/build.properties, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/NewOWL2SnippetTestIT.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OWL2UnitTests.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java
Bugfix/lexevs 3017 Merging v6.5.0 branch to master branch.
This updates the master branch with the latest 6.5.0.1.FINAL changes
=> Bugfix/lexevs 3017 Merging v6.5.0 branch to master branch.

lbImpl/src/org/LexGrid/LexBIG/Impl/loaders/BaseLoader.java, lbImpl/src/org/LexGrid/LexBIG/Impl/loaders/SourceAssertedVStoCodingSchemLoaderImpl.java, lbImpl/src/org/LexGrid/LexBIG/Impl/loaders/SourceAssertedValueSetToSchemeBatchLoader.java, lbInterfaces/src/org/LexGrid/LexBIG/Extensions/Load/SourceAssertedVStoCodingSchemeLoader.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/bugs/GForge21567.java, lexevs-dao/src/main/java/org/lexevs/system/ResourceManager.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/assertedValueSets/EntityToRVSTransformer.java
Fixing Extraneous Thread Creation issues.  We disable some thread making functions that no longer have a purpose and remove the runnable inner class and all members dependent on it.
=> Bugfix/lexevs 3067  Fixing Extraneous Thread Creation issues

lbPackager/build.properties
LEXEVS-3177 Updated version to 6.5.0.2.FINAL
=> LEXEVS-3177 Updated version to 6.5.0.2.FINAL

lbTest/resources/testData/owl2/OWLPrefsLoadAnonAsAssocPF2SetTopNodes.XML, lbTest/resources/testData/owl2/OWLPrefsLoadAnonAsAssocPF2SetTopNodesByNameToCode.XML, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/DataLoadTestBaseSnippet2.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/NewOWL2SnippetTestIT.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/OWL2PrimitivesSnippetTestIT.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/OWL2SpecialCaseSnippetTestIT.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LGConstants.java
LEXEVS-3222 OWL2 Load Support for supportedSources
=> LEXEVS-3222 OWL2 Load Support for supportedSources

lbPackager/build.properties
LEXEVS-3235 Updated version to 6.5.0.3.FINAL
=> LEXEVS-3235 Updated version to 6.5.0.3.FINAL

lbPackager/build.properties
LEXEVS-3270 - Updating version to 6.5.0.4.FINAL
=> LEXEVS-3270 - Updating version to 6.5.0.4.FINAL

lbAdmin/scripts/LoadManifest.bat, lbAdmin/scripts/LoadManifest.sh, lbAdmin/src/org/LexGrid/LexBIG/admin/LoadManifest.java, lbTest/resources/testData/owl2/OWLPrefsLoadAnonAsAssocPF2SetTopNodes.XML, lbTest/resources/testData/owl2/OWLPrefsLoadAnonAsAssocPF2SetTopNodesByNameToCode.XML, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/DataLoadTestBaseSnippet2.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/NewOWL2SnippetTestIT.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/OWL2PrimitivesSnippetTestIT.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/OWL2SpecialCaseSnippetTestIT.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LGConstants.java
Bugfix/lexevs 3281 merging 6.5.0 loader changes to dev branch
=> Bugfix/lexevs 3281 merging 6.5.0 loader changes to dev branch

lbTest/resources/testData/owl2/owl2-special-cases-Namespaces.owl, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/DataLoadTestBaseSpecialCases.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/DataLoadTestBaseSpecialCasesNamespace.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/OWL2SpecialCasesNamespaceTestIT.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/function/LexBIGServiceTestCase.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/CleanUpTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/LoadTestDataTest.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java
Bugfix/lexevs 3254 Updating default namespace in OWL2 load
=> Bugfix/lexevs 3254 Updating default namespace in OWL2 load

lbPackager/build.properties
LEXEVS-3310 - Updated release version to 6.5.0.5.FINAL
=> LEXEVS-3310 - Updated release version to 6.5.0.5.FINAL

lbTest/resources/testData/owl2/OWLPrefsLoadAnonAsAssocPF2SetTopNodes.XML, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java
LEXEVS-3252 Update source and representational form to support use of the property code to specify the property
=> LEXEVS-3252 Update source and representational form to support use of the property code to specify the property

lexevs-dao/src/main/java/org/lexevs/dao/database/service/valuesets/LexEVSTreeItem.java
LEXEVS-3301 Added public getter method for the _ns attribute.
=> LEXEVS-3301 Added public getter method for the _ns attribute.

lbPackager/build.properties
LEXEVS-3342 - Updated version to 6.5.0.6.FINAL
=> LEXEVS-3342 - Updated version to 6.5.0.6.FINAL

lbPackager/build.properties
LEXEVS-3349 - Updated version to 6.5.1.SNAPSHOT.2
=> LEXEVS-3349 - Updated version to 6.5.1.SNAPSHOT.2

lbTest/resources/testData/owl2/OWLPrefsLoadAnonAsAssocPF2SetTopNodes.XML, lbTest/resources/testData/owl2/owl2-special-cases-Namespaces.owl, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/DataLoadTestBaseSpecialCasesNamespace.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/OWL2SpecialCasesNamespaceTestIT.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/function/LexBIGServiceTestCase.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/CleanUpTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/LoadTestDataTest.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java
Bugfix/lexevs 3368 Merge 6.5.0 updates to the DEV branch
=> Bugfix/lexevs 3368 Merge 6.5.0 updates to the DEV branch

lbPackager/build.properties
LEXEVS-3389 - Updated version to 6.5.1.SNAPSHOT.3
=> LEXEVS-3389 - Updated version to 6.5.1.SNAPSHOT.3

lbPackager/build.properties
LEXEVS-3421 - Updated version to 6.5.1.SNAPSHOT.4
=> LEXEVS-3421 - Updated version to 6.5.1.SNAPSHOT.4

lbTest/src/test/java/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/MappingExtensionImplTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/load/meta/GenericPropertySourceQualifierTestIT.java
We have a couple of Unit tests that were designed to act as reminders of issues.  We've moved these issues to the backlog where they can be prioritized and completed.
=> LEXEVS-3463. Updating unit tests to reflect continuous integration practise

lbTest/src/test/java/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/MappingExtensionImplTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/load/meta/GenericPropertySourceQualifierTestIT.java
These JIRA items will be slated for completion as priority allows.
=> LEXEVS-3470.  Removing placeholder unit tests and moving them to JIRA

lbTest/resources/testData/owl2/owl2-special-cases-Defined-Annotated.owl, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/OWL2SpecialCaseSnippetTestIT.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LGConstants.java
LEXEVS-3468 Updates to OWL2 loader to fix isActive status
=> LEXEVS-3468 Updates to OWL2 loader to fix isActive status

lbPackager/build.properties
LEXEVS-3502 Updated LexEVS version to 6.5.0.7.FINAL
=> LEXEVS-3502 Updated LexEVS version to 6.5.0.7.FINAL

lbImpl/src/org/LexGrid/LexBIG/Impl/Extensions/tree/json/ChildPagingJsonConverter.java, lbImpl/src/org/LexGrid/LexBIG/Impl/Extensions/tree/model/LexEvsTreeNode.java, lbImpl/src/org/LexGrid/LexBIG/Impl/Extensions/tree/transform/AssociationListToTreeNodeList.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/Extensions/tree/model/LexEvsTreeNodeJsonNameSpaceTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/Extensions/tree/test/LexEvsTreeTestBase.java, lbTest/src/test/java/org/lexevs/tree/test/LexEvsTreeTestBase.java
Bugfix/lexevs 2183 TreeService API - don't return anonymous nodes
=> Bugfix/lexevs 2183 TreeService API - don't return anonymous nodes

lexevs-dao/src/main/java/org/lexevs/dao/database/service/valuesets/ValueSetHierarchyServiceImpl.java, lgValueSets/src/org/lexgrid/valuesets/sourceasserted/impl/SourceAssertedValueSetHierarchyServicesImpl.java
LEXEVS-3524 - Allow VS Hierarchy to be resolved from Source Asserted VS API
=> LEXEVS-3524 - Allow VS Hierarchy to be resolved from Source Asserted VS API

lbImpl/src/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/search/BuildMatchAlgorithmQuery.java, lbImpl/src/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/search/LexEVSSourceAssertedSearchServices.java, lbImpl/src/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/search/SearchScoreDocIterator.java, lbImpl/src/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/search/SourceAssertedScoreDocTransformer.java, lbImpl/src/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/search/SourceAssertedScoreDocTransformerExecutor.java, lbImpl/src/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/search/SourceAssertedValueSetScoreDocIteratorWrapper.java, lbImpl/src/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/search/SourceAssertedValueSetSearchExtensionImpl.java, lbImpl/src/org/LexGrid/LexBIG/Impl/LexBIGServiceImpl.java, lbImpl/src/org/LexGrid/LexBIG/Impl/helpers/ResolvedConceptReferenceTransformer.java, lbImpl/src/org/LexGrid/LexBIG/Impl/helpers/Transformer.java, lbImpl/src/org/LexGrid/LexBIG/Impl/helpers/TransformerExecutor.java, lbInterfaces/src/org/LexGrid/LexBIG/Extensions/Generic/SearchExtension.java, lbInterfaces/src/org/LexGrid/LexBIG/Extensions/Generic/SourceAssertedValueSetSearchExtension.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/search/SourceAssertedValueSetSearchExtensionTest.java
Search API for the Asserted Value Set Index.  Modeled after the Simple Search API.
=> Bugfix/lexevs 3475  Creating an Asserted Value Set Search API

lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/assertedValueSets/AssertedValueSetIndexSupport.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/assertedValueSets/SourceAssertedValueSetSearchIndexServiceTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java, lbTest/src/test/java/org/LexGrid/valuesets/sourceasserted/impl/SourceAssertedVSIteratorTest.java, lbTest/src/test/java/org/LexGrid/valuesets/sourceasserted/impl/SourceAssertedValueSetTest.java, lbTest/src/test/java/org/lexevs/dao/database/ibatis/valuesets/IbatisSourceAssertedValueSetDaoTest.java, lbTest/src/test/java/org/lexevs/dao/index/indexer/SourceAssertedIndexerTest.java, lexevs-dao/src/main/java/org/lexevs/dao/database/access/valuesets/SourceAssertedValueSetDao.java, lexevs-dao/src/main/java/org/lexevs/dao/database/ibatis/valuesets/IbatisSourceAssertedValueSetDao.java, lexevs-dao/src/main/java/org/lexevs/dao/database/service/valuesets/AssertedValueSetService.java, lexevs-dao/src/main/java/org/lexevs/dao/database/service/valuesets/AssertedValueSetServiceImpl.java, lexevs-dao/src/main/java/org/lexevs/dao/index/indexer/AssertedValueSetEntityIndexer.java, lexevs-dao/src/main/java/org/lexevs/dao/index/indexer/SourceAssertedValueSetIndexCreator.java, lexevs-dao/src/main/resources/ibatis/v20/entityAssnsToEntity.xml, lgUtil/src/org/LexGrid/util/assertedvaluesets/AssertedValueSetServices.java, lgValueSets/src/org/lexgrid/valuesets/sourceasserted/impl/AssertedValueSetEntityResolver.java, lgValueSets/src/org/lexgrid/valuesets/sourceasserted/impl/AssertedValueSetResolvedConceptReferenceIterator.java, lgValueSets/src/org/lexgrid/valuesets/sourceasserted/impl/SourceAssertedValueSetServiceImpl.java
Dynamically iterates against source in database to return collections and individual objects according to the idea of terminology source assertions of value sets.
=> Bugfix/lexevs 3547  Implementation of an iterator for asserted valueset

lbImpl/src/org/LexGrid/LexBIG/Impl/LexBIGServiceImpl.java, lbImpl/src/org/LexGrid/LexBIG/Impl/loaders/LexGridMultiLoaderImpl.java, lbImpl/src/org/LexGrid/LexBIG/Impl/loaders/LexGridMultiResolvedValueSetLoaderImpl.java, lbPackager/build.properties
Bugfix/lexevs 3587 Update Lexevs value set loader to work for CTS2 in memory tests
=> Bugfix/lexevs 3587 Update Lexevs value set loader to work for CTS2 in memory tests

lbPackager/build.properties
LEXEVS-3597 Updated version to 6.5.1.SNAPSHOT.6
=> LEXEVS-3597 Updated version to 6.5.1.SNAPSHOT.6

lbPackager/build.properties
LEXEVS-3630 - Updated version to 6.5.1.SNAPSHOT.7
=> LEXEVS-3630 - Updated version to 6.5.1.SNAPSHOT.7

lbTest/resources/testData/owl2/owl2-special-cases-Defined-AnnotatedExpVS.owl, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/assertedValueSets/CleanUpResolvedValueSetUpdateLoads.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/assertedValueSets/ExternalResolvedValueSetIndexingTest.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/assertedValueSets/LoadAndUpdateSourceAssertedValueSetsTest.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/assertedValueSets/NCItSourceAssertedValueSetUpdateServiceTest.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/assertedValueSets/SourceAssertedValueSetSearchIndexServiceTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/search/SourceAssertedValueSetSearchExtensionTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java, lbTest/src/test/java/org/LexGrid/valueset/test/VDAllTests.java, lbTest/src/test/java/org/LexGrid/valuesets/sourceasserted/impl/SourceAssertedValueSetTest.java, lexevs-dao/src/main/java/org/lexevs/dao/index/indexer/AssertedValueSetEntityIndexer.java, lexevs-dao/src/main/java/org/lexevs/dao/index/service/search/SourceAssertedValueSetSearchIndexService.java, lgUtil/src/org/LexGrid/util/assertedvaluesets/AssertedValueSetServices.java, lgValueSets/src/org/lexgrid/resolvedvalueset/impl/ExternalResolvedValueSetIndexService.java
Bugfix/lexevs 3518  Adding external value sets to value set index
=> Bugfix/lexevs 3518  Adding external value sets to value set index

lexevs-dao/resources/config/lbconfig.props, lexevs-dao/src/main/java/org/lexevs/system/constants/SystemVariables.java, lexevs-dao/src/main/resources/ibatis/v20/entityAssnsToEntity.xml, lexevs-dao/src/test/resources/lbconfig.props, lgValueSets/src/org/lexgrid/resolvedvalueset/LexEVSResolvedValueSetService.java, lgValueSets/src/org/lexgrid/resolvedvalueset/impl/LexEVSResolvedValueSetServiceImpl.java
LEXEVS-3655 Updates for asserted value set to work with CTS2
=> LEXEVS-3655 Updates for asserted value set to work with CTS2

lbTest/src/test/java/org/LexGrid/valuesets/sourceasserted/impl/SourceAssertedVSIteratorTest.java, lexevs-dao/src/main/java/org/lexevs/paging/AbstractAssertedVSResolvedConceptReferenceIterator.java, lgValueSets/src/org/lexgrid/valuesets/sourceasserted/impl/AssertedValueSetResolvedConceptReferenceIterator.java
=> LEXEVS-3689. Fixing and issue with using hasNext with paging form of next

lbPackager/build.properties
LEXEVS-3707 Updated to version  Snapshot.11
=> LEXEVS-3707 Updated to version  Snapshot.11

lbPackager/build.properties
LEXEVS-3717 - Updated version to snapshot.12
=> LEXEVS-3717 - Updated version to snapshot.12

lbPackager/build.properties, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/assertedValueSets/AssertedValueSetTagTest.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/assertedValueSets/LoadAndUpdateSourceAssertedValueSetsTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java, lexevs-dao/src/main/java/org/lexevs/dao/database/service/valuesets/AssertedValueSetServiceImpl.java, lexevs-dao/src/main/java/org/lexevs/system/constants/SystemVariables.java, lgUtil/src/org/LexGrid/util/assertedvaluesets/AssertedValueSetParameters.java
LEXEVS-3743 Defaulting asserted value set tag to PRODUCTION.
=> LEXEVS-3743 Defaulting asserted value set tag to PRODUCTION.

lbPackager/build.properties
LEXEVS-3757 - Updated build to SNAPSHOT.14
=> LEXEVS-3757 - Updated build to SNAPSHOT.14

lbAdmin/scripts/LoadMetaBatch.bat, lbAdmin/scripts/LoadMetaBatch.sh
LEXEVS-3781 - Updated script Xmx value to 6G.
=> LEXEVS-3781 - Updated script Xmx value to 6G.

lbPackager/build.properties
LEXEVS-3766 - Updated version to 6.5.1.RC.1
=> LEXEVS-3766 - Updated version to 6.5.1.RC.1

lbPackager/build.properties
LEXEVS-3885 - Updated version to 6.5.1RC.2
=> LEXEVS-3885 - Updated version to 6.5.1RC.2

lbPackager/build.properties
LEXEVS-3478 - Updated version to 6.5.1.FINAL.
=> LEXEVS-3478 - Updated version to 6.5.1.FINAL.

lbTest/src/test/java/org/LexGrid/LexBIG/Impl/dataAccess/CleanUpUtilityTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java
Bugfix/lexevs 3737 - Adding cleanup tests back into test harness.
=> Bugfix/lexevs 3737 - Adding cleanup tests back into test harness.

lbGUI/src/org/LexGrid/LexBIG/gui/load/LoaderExtensionShell.java
LEXEVS-3973 - Initializing the AssertedValueSetParameters.
=> LEXEVS-3973 - Initializing the AssertedValueSetParameters.

lbPackager/build.properties
LEXEVS-3978 - Updated version to 6.5.1.1.SNAPSHOT.1
=> LEXEVS-3978 - Updated version to 6.5.1.1.SNAPSHOT.1

lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/assertedValueSets/EntityToVSDTransFormerTest.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/assertedValueSets/EntityToVSDTransformer.java
=> Revert "LEXEVS-4056. Committing a fix for mappings in value set transform"

lbPackager/build.properties
Bugfix/lexevs 4061 - Updated version to 6.5.1.1.SNAPSHOT.2
=> Bugfix/lexevs 4061 - Updated version to 6.5.1.1.SNAPSHOT.2

lbAdmin/scripts/LoadOWL2.bat, lbAdmin/scripts/LoadOWL2.sh, lbAdmin/src/org/LexGrid/LexBIG/admin/LoadOWL2.java
Bugfix/lexevs 4014 Added ability to load metadata as part of the LoadOWL2 script.
=> Bugfix/lexevs 4014 Added ability to load metadata as part of the LoadOWL2 script.

lbAdmin/.classpath, lbAdmin/ivy.xml, lbAdmin/scripts/LoadUmlsBatch.bat, lbAdmin/scripts/LoadUmlsBatch.sh, lbAdmin/src/org/LexGrid/LexBIG/admin/LoadUmlsBatchWithMetadata.java, umls-loader/src/main/java/org/lexgrid/loader/umls/launch/UmlsBatchLoaderLauncher.java
LEXEVS-4012 - Added ability to load metadata as part of the LoadUmlsBatch script.
=> LEXEVS-4012 - Added ability to load metadata as part of the LoadUmlsBatch script.

lbAdmin/scripts/LoadOBO.bat, lbAdmin/scripts/LoadOBO.sh, lbAdmin/src/org/LexGrid/LexBIG/admin/LoadOBO.java
LEXEVS-4011 Added ability to load metadata as part of the LoadOBO script.
=> LEXEVS-4011 Added ability to load metadata as part of the LoadOBO script.

lbAdmin/scripts/LoadLgXML.bat, lbAdmin/scripts/LoadLgXML.sh, lbAdmin/src/org/LexGrid/LexBIG/admin/LoadLgXML.java
LEXEVS-4010 - Added ability to load metadata as part of the LoadLgXML script.
=> LEXEVS-4010 - Added ability to load metadata as part of the LoadLgXML script.

lbAdmin/scripts/LoadMrMap.bat, lbAdmin/scripts/LoadMrMap.sh, lbAdmin/src/org/LexGrid/LexBIG/admin/LoadMrMap.java
LEXEVS-4009 - Added ability to load metadata as part of the LoadMrMap script.
=> LEXEVS-4009 - Added ability to load metadata as part of the LoadMrMap script.

lbAdmin/scripts/LoadOBO.bat, lbAdmin/scripts/LoadOBO.sh, lbAdmin/src/org/LexGrid/LexBIG/admin/LoadOBO.java
LEXEVS-4011 Loader: Allow metadata to be loaded as part of the LoadOBO script
=> LEXEVS-4011 Loader: Allow metadata to be loaded as part of the LoadOBO script

lbPackager/build.properties
LEXEVS-4070 - Updated version to snapshot.3.
=> LEXEVS-4070 - Updated version to snapshot.3.

lbImpl/src/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/LexBIGServiceConvenienceMethodsImpl.java, lbInterfaces/src/org/LexGrid/LexBIG/Extensions/Generic/LexBIGServiceConvenienceMethods.java, lbTest/resources/testData/owl2/owl2-special-cases-Defined-Annotated.owl, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/LexBIGServiceConvenienceMethodsImplTest.java, lbTest/src/test/java/org/LexGrid/valueset/impl/LexEVSValueSetDefServicesImplTest.java, lexevs-dao/src/main/java/org/lexevs/dao/database/ibatis/association/IbatisAssociationDao.java, lexevs-dao/src/main/resources/ibatis/v20/entityAssnsToEntity.xml
Defining the domain as a hierarchy and using existing LexEVS methods with a few tweaks and updates.
=> Bugfix/lexevs 4093  Creating a convenience method to restrict a search to a given domain

lbGUI/src/org/LexGrid/LexBIG/gui/LoadExportBaseShell.java, lbGUI/src/org/LexGrid/LexBIG/gui/load/LoaderExtensionShell.java
LEXEVS-3988 - Added option to load metadata after a terminology is loaded
=> LEXEVS-3988 - Added option to load metadata after a terminology is loaded

lbPackager/build.properties
LEXEVS-4121 updated to snapshot 4
=> LEXEVS-4121 updated to snapshot 4

lbPackager/build.properties
LEXEVS-4142 Updated build version to 6.5.1.1.FINAL
=> LEXEVS-4142 Updated build version to 6.5.1.1.FINAL

lbImpl/src/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/LexBIGServiceConvenienceMethodsImpl.java, lbInterfaces/src/org/LexGrid/LexBIG/Extensions/Generic/LexBIGServiceConvenienceMethods.java, lbTest/resources/testData/owl2/owl2-special-cases-Defined-Annotated.owl, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/LexBIGServiceConvenienceMethodsImplTest.java, lbTest/src/test/java/org/LexGrid/valueset/impl/LexEVSValueSetDefServicesImplTest.java
Adding capability to adjust to source, search algorithm, and preferred presentation or other presentation type.
=> Bugfix/lexevs 4115  Updates to feature returning search results from a given domain

lbPackager/build.properties
Bugfix/lexevs 4215 Updated Version to 6.5.1.2.FINAL
=> Bugfix/lexevs 4215 Updated Version to 6.5.1.2.FINAL

lexevs-dao/src/main/java/org/lexevs/dao/database/operation/DefaultLexEvsDatabaseOperations.java, lexevs-dao/src/main/resources/sql/lexevs/codingscheme-schema.xml, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/CreateUtils.java
LEXEVS-3955 - Updated database to allow for larger indexes (with Barracuda file format).
=> LEXEVS-3955 - Updated database to allow for larger indexes (with Barracuda file format).

lbModel/master.preferences/OWLLoadPreferences.xsd, lbPackager/build.properties, lbTest/resources/testData/owl2/OWLTransPrefsLoadAnonAsAssocPF2SetTopNodes.XML, lbTest/resources/testData/owl2/owl2-special-cases-Defined-Annotated.owl, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/OWL2SpecialCasesPreferencesLoad.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/AssociationManager.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/AssociationWrapper.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LGConstants.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/PreferenceManager.java
Bugfix/lexevs 4215 merging 6.5.1 branch changes into Dev.
=> Bugfix/lexevs 4215 merging 6.5.1 branch changes into Dev.

lbModel/master.preferences/OWLLoadPreferences.xsd, lbTest/resources/testData/owl2/OWLTransPrefsLoadAnonAsAssocPF2SetTopNodes.XML, lbTest/resources/testData/owl2/owl2-special-cases-Defined-Annotated.owl, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/OWL2SpecialCasesPreferencesLoad.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/AssociationManager.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/AssociationWrapper.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LGConstants.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/PreferenceManager.java
Bugfix/lexevs 4241 - merging LEXEVS-4129 changes to 6.5.1
=> Bugfix/lexevs 4241 - merging LEXEVS-4129 changes to 6.5.1 

lbPackager/build.properties
LEXEVS-4247 Updated version to 6.5.1.3.FINAL
=> LEXEVS-4247 Updated version to 6.5.1.3.FINAL

lbPackager/build.properties
LEXEVS-4249 - Updated version to 6.5.2.RC.2.
=> LEXEVS-4249 - Updated version to 6.5.2.RC.2.

lbImpl/src/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/mapping/MappingExtensionImpl.java, lbImpl/src/org/LexGrid/LexBIG/Impl/loaders/MrmapRRFLoader.java, lbImpl/src/org/LexGrid/LexBIG/Utility/ServiceUtility.java, lbInterfaces/src/org/LexGrid/LexBIG/Extensions/Generic/MappingExtension.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/mrmap/TestLoadMrMap2Mappings.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java, lbTest/src/test/java/org/lexevs/dao/database/access/codednodegraph/MappingCodedNodeDaoFunctionTest.java, lexevs-dao/src/main/java/org/lexevs/dao/database/access/codednodegraph/CodedNodeGraphDao.java, lexevs-dao/src/main/java/org/lexevs/dao/database/ibatis/codednodegraph/IbatisCodedNodeGraphDao.java, lexevs-dao/src/main/java/org/lexevs/dao/database/ibatis/parameter/SourceAndTargetMappingPrefixedParameter.java, lexevs-dao/src/main/resources/ibatis/v20/entityAssnsToEntity.xml, lgModel/src/org/LexGrid/custom/relations/TerminologyMapBean.java
Bugfix/lexevs 4299 - merging dev to 6.5.2
=> Bugfix/lexevs 4299 - merging dev to 6.5.2

lbPackager/build.properties
LEXEVS-4311 - Updated version to 6.5.2.RC.4
=> LEXEVS-4311 - Updated version to 6.5.2.RC.4

lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/assertedValueSets/SourceAssertedValueSetSearchIndexServiceTest.java, lbTest/src/test/java/org/LexGrid/valueset/impl/LexEVSResolvedValueSetTest.java, lexevs-dao/src/main/java/org/lexevs/dao/database/access/valuesets/SourceAssertedValueSetDao.java, lexevs-dao/src/main/java/org/lexevs/dao/database/ibatis/valuesets/IbatisSourceAssertedValueSetDao.java, lexevs-dao/src/main/java/org/lexevs/dao/database/service/valuesets/AssertedValueSetService.java, lexevs-dao/src/main/java/org/lexevs/dao/database/service/valuesets/AssertedValueSetServiceImpl.java, lexevs-dao/src/main/resources/ibatis/v20/entityAssnsToEntity.xml, lgValueSets/src/org/lexgrid/resolvedvalueset/LexEVSResolvedValueSetService.java, lgValueSets/src/org/lexgrid/resolvedvalueset/impl/LexEVSResolvedValueSetServiceImpl.java, lgValueSets/src/org/lexgrid/valuesets/sourceasserted/SourceAssertedValueSetService.java, lgValueSets/src/org/lexgrid/valuesets/sourceasserted/impl/SourceAssertedValueSetServiceImpl.java
Bugfix/lexevs 4345 Add API call to get asserted value set by name
=> Bugfix/lexevs 4345 Add API call to get asserted value set by name

lbPackager/build.properties
Bugfix/lexevs 4330 Updated version to 6.5.2.RC.5
=> Bugfix/lexevs 4330 Updated version to 6.5.2.RC.5

lbImpl/src/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/mapping/MappingExtensionImpl.java, lbPackager/build.properties, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/assertedValueSets/SourceAssertedValueSetSearchIndexServiceTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java, lbTest/src/test/java/org/LexGrid/valueset/impl/LexEVSResolvedValueSetTest.java, lbTest/src/test/java/org/LexGrid/valuesets/sourceasserted/impl/TestAssertedValueSetInitialization.java, lbTest/src/test/java/org/lexevs/dao/database/access/codednodegraph/MappingCodedNodeDaoFunctionTest.java, lexevs-dao/src/main/java/org/lexevs/dao/database/access/valuesets/SourceAssertedValueSetDao.java, lexevs-dao/src/main/java/org/lexevs/dao/database/ibatis/valuesets/IbatisSourceAssertedValueSetDao.java, lexevs-dao/src/main/java/org/lexevs/dao/database/service/valuesets/AssertedValueSetService.java, lexevs-dao/src/main/java/org/lexevs/dao/database/service/valuesets/AssertedValueSetServiceImpl.java, lexevs-dao/src/main/java/org/lexevs/dao/database/service/valuesets/ValueSetHierarchyServiceImpl.java, lexevs-dao/src/main/resources/ibatis/v20/entityAssnsToEntity.xml, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/assertedValueSets/EntityToVSDTransformer.java, lgValueSets/src/org/lexgrid/resolvedvalueset/LexEVSResolvedValueSetService.java, lgValueSets/src/org/lexgrid/resolvedvalueset/impl/LexEVSResolvedValueSetServiceImpl.java, lgValueSets/src/org/lexgrid/valuesets/sourceasserted/SourceAssertedValueSetService.java, lgValueSets/src/org/lexgrid/valuesets/sourceasserted/impl/SourceAssertedValueSetServiceImpl.java
Bugfix/lexevs 4353 merging 6.5.2 to Dev
=> Bugfix/lexevs 4353 merging 6.5.2 to Dev

lbAdmin/scripts/ListLexevsVersion.sh, lbAdmin/src/org/LexGrid/LexBIG/admin/ListLexevsVersion.java, lbImpl/src/org/LexGrid/LexBIG/Impl/LexBIGServiceImpl.java, lbImpl/src/org/LexGrid/LexBIG/Impl/LexEVSVersion.java, lbInterfaces/src/org/LexGrid/LexBIG/LexBIGService/LexBIGService.java, lbPackager/build.xml, lbPackager/files/LexEVSVersion.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/LexBIGServiceConvenienceMethodsImplTest.java
Bugfix/lexevs 3732 Adding lexevs version API
=> Bugfix/lexevs 3732 Adding lexevs version API

lbPackager/build.properties
LEXEVS-4383 - Updated version to 6.5.2.RC.6
=> LEXEVS-4383 - Updated version to 6.5.2.RC.6

lbPackager/build.properties
LEXEVS-4453 Updated build version to 6.5.2.FINAL
=> LEXEVS-4453 Updated build version to 6.5.2.FINAL

lbPackager/build.properties
LEXEVS-4502 - Updated version to indicate a Dev snapshot -- SNAPSHOT.DEV.SPRINT106.2019.04.17
=> LEXEVS-4502 - Updated version to indicate a Dev snapshot

lbPackager/build.properties
Bugfix/lexevs 4527 Updated version to new DEV snapshot.
=> Bugfix/lexevs 4527 Updated version to new DEV snapshot.

lbPackager/build.properties
LEXEVS-4562 - Updated build version for new dev snapshot.
=> LEXEVS-4562 - Updated build version for new dev snapshot.

lbPackager/build.properties
Bugfix/lexevs 4577 Updated build number for DEV Snapshot
=> Bugfix/lexevs 4577 Updated build number for DEV Snapshot

lbTest/resources/testData/owl2/OWLTransPrefsLoadAnonAsAssocPF2SetTopNodes.XML, lbTest/resources/testData/owl2/owl2-special-cases-Defined-Annotated.owl, lexevs-dao/src/main/java/org/lexevs/dao/database/service/valuesets/ValueSetHierarchyServiceImpl.java
Bugfix/lexevs 4634 - updating init() call to initialize asserted value set parameters
=> Bugfix/lexevs 4634 - updating init() call to initialize asserted value set parameters

lbPackager/build.properties
LEXEVS-4612 - Updated build properties to 6.5.3.RC.3
=> LEXEVS-4612 - Updated build properties to 6.5.3.RC.3

lbTest/resources/testData/owl2/OWLPrefsLoadAnonAsAssocPF2SetTopNodes.XML, lbTest/resources/testData/owl2/OWLTransPrefsLoadAnonAsAssocPF2SetTopNodes.XML, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/OWL2SpecialCaseSnippetTestIT.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java
Bugfix/lexevs 4673 Add ability to enter codes for MatchConceptStatus in the Preference xml file
=> Bugfix/lexevs 4673 Add ability to enter codes for MatchConceptStatus in the Preference xml file

lbPackager/build.properties
LEXEVS-4717 Update version to 6.5.3.FINAL
=> LEXEVS-4717 Update version to 6.5.3.FINAL

lexevs-dao/src/main/java/org/lexevs/dao/database/datasource/ErrorReportingGraphDbDataSourceManager.java, lexevs-dao/src/main/java/org/lexevs/dao/database/datasource/GraphDbDataSourceInstance.java, lexevs-dao/src/main/java/org/lexevs/dao/database/graph/LexEVSRelsToGraphDao.java, lexevs-dao/src/main/java/org/lexevs/system/constants/SystemVariables.java
Bugfix/lexevs 4745 Improve robustness of graph database startup in LexEVS
=> Bugfix/lexevs 4745 Improve robustness of graph database startup in LexEVS

lbAdmin/src/org/LexGrid/LexBIG/admin/LoadGraphDatabase.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/graphdb/TestGraphQueryMethods.java, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/graphdb/TestLexEVSRelsToGraphDao.java, lexevs-dao/src/main/java/org/lexevs/dao/database/datasource/ErrorReportingGraphDbDataSourceManager.java, lexevs-dao/src/main/java/org/lexevs/dao/database/graph/LexEVSRelsToGraphDao.java, lexevs-dao/src/main/java/org/lexevs/dao/database/service/graphdb/GraphingDataBaseServiceImpl.java
Bugfix/lexevs 4742 Add ability to load version specific loads to the graph loader.
=> Bugfix/lexevs 4742 Add ability to load version specific loads to the graph loader.

lbImpl/src/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/graph/NodeGraphResolutionExtensionImpl.java, lbInterfaces/src/org/LexGrid/LexBIG/Extensions/Generic/NodeGraphResolutionExtension.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/graph/NodeGraphResolutionExtensionTest.java, lbTest/src/test/java/org/lexevs/dao/database/graph/rest/client/LexEVSSpringRestClientImplPerformanceITTest.java, lbTest/src/test/java/org/lexevs/dao/database/graph/rest/client/LexEVSSpringRestClientImplTest.java, lexevs-dao/src/main/java/org/lexevs/dao/database/graph/rest/client/LexEVSSpringRestClientImpl.java
This also includes a fairly major refactor of the code base, reducing code complexity.
=> Bugfix/lexevs 4792  Adding capability for depth control to graph queries

lbPackager/build.properties
LEXEVS-4881 - Updated version for snapshot 130
=> LEXEVS-4881 - Updated version for snapshot 130

lbImpl/src/org/LexGrid/LexBIG/Impl/LexEVSVersion.java, lbPackager/build.properties
LEXEVS-4888 Updated version to 6.5.4.RC.1
=> LEXEVS-4888 Updated version to 6.5.4.RC.1

lbPackager/build.properties
LEXEVS-4909 Updated version to 6.5.4.FINAL
=> LEXEVS-4909 Updated version to 6.5.4.FINAL

lbPackager/build.properties, meta-loader/src/main/resources/metaLoader.xml
Bugfix/lexevs 4964 Merging Metathaurus Load changes( LEXEVS-4966) to 6.5.4
=> Bugfix/lexevs 4964 Merging Metathaurus Load changes to 6.5.4

lbAdmin/scripts/LoadNCItMgr.sh, lgValueSets/src/org/lexgrid/valuesets/admin/LoadNCITMgr.java
Feature/lexevs 4992 New NCI Thesaurus mgr script
=> Feature/lexevs 4992 New NCI Thesaurus mgr script

lbAdmin/scripts/LoadNCIHistory.bat, lbAdmin/scripts/LoadNCIHistory.sh, lbAdmin/scripts/LoadOWL2.bat, lbAdmin/scripts/LoadOWL2.sh, lbAdmin/src/org/LexGrid/LexBIG/admin/LoadOWL2.java
=> LEXEVS-5046 Increased Java heap size and added preferences in the example call.

lbAdmin/scripts/LoadNCIHistory.bat, lbAdmin/scripts/LoadNCIHistory.sh, lbAdmin/scripts/LoadOWL2.bat, lbAdmin/scripts/LoadOWL2.sh, lbAdmin/src/org/LexGrid/LexBIG/admin/LoadOWL2.java, lbPackager/build.properties, lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OWLUnitTests.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/Extensions/tree/model/LexEvsTreeNodeJsonNameSpaceTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/Extensions/tree/test/TestGetTree.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/bugs/GForge20875.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/bugs/GForge26741.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/bugs/GForge29842.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/bugs/GForge29860.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/bugs/TestBugFixes.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/function/codednodegraph/RestrictToEntityTypesTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/function/query/TestDiscoverAvailableVocabulariesandVersions.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/function/query/TestEnumerateProperties.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/function/query/TestHierarchyAPI.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/function/query/TestOWLLoaderPreferences.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/LoadTestDataTest.java, lbTest/src/test/java/org/lexevs/dao/index/operation/ManifestLoadWithAssociationTest.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java, lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LGConstants.java
LEXEVS-5051 Merging loader changes to 6.5.4 for RC2.
=> LEXEVS-5051 Merging loader changes to 6.5.4 for RC2.

lbPackager/ivysettings.xml
LEXEVS-5087 - updated ivy setting to https
=> LEXEVS-5087 - updated ivy setting to https

lbTest/resources/testData/pizza.owl, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/bugs/GForge29772.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/bugs/GForge29839.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/bugs/GForge29840.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/bugs/GForge29841.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/bugs/GForge29842.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/bugs/GForge29860.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/bugs/GForge29940.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/function/LexBIGServiceTestCase.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/CleanUpTest.java, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/LoadTestDataTest.java
This required some adjustment to our testing strategy since this is created and loaded in a new OWL format
=> LEXEVS-5088.  Adding the latest pizza.owl to our test base.  

.gitignore, abstract-rrf-loader/src/main/resources/rrfBaseLoader.xml, abstract-rrf-loader/src/main/resources/rrfBaseLoaderStaging.xml, abstract-rrf-loader/src/main/resources/rrfReaders.xml, lbImpl/src/main/resources/deptreeServiceContext.xml, lbImpl/src/main/resources/treeServiceContext.xml, lbPackager/build.properties, lbPackager/common-build.xml, lbTest/src/test/java/org/LexGrid/LexBIG/Impl/Extensions/tree/test/treeServiceContext.xml, lbTest/src/test/java/org/lexevs/tree/test/treeServiceContext.xml, lexevs-dao/ivy.xml, lexevs-dao/src/main/java/org/lexevs/dao/database/access/DaoManager.java, lexevs-dao/src/main/java/org/lexevs/dao/database/datasource/ErrorReportingGraphDbDataSourceManager.java, lexevs-dao/src/main/resources/ibatis/v20/v20SqlMaps.xml, lexevs-dao/src/main/resources/lexevsCache.xml, lexevs-dao/src/main/resources/lexevsDao.xml, lgConverter/ivy.xml, loader-framework-core/src/main/resources/baseLoader.xml, loader-framework-core/src/main/resources/repositories.xml, loader-framework-core/src/main/resources/writers.xml, loader-framework-core/src/test/java/org/lexgrid/loader/listener/StepCompletionListenerTest.java, meta-loader/src/main/resources/metaLoader.xml, meta-loader/src/main/resources/metaLoaderStaging.xml, umls-loader/src/main/resources/medrtUmlsLoader.xml, umls-loader/src/main/resources/umlsLoader.xml, umls-loader/src/main/resources/umlsLoaderStaging.xml
remove spring-asm and javax-inject.
=> Lexevs 5294
