lexevs/lexevs

- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/LoadTestDataTest.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Utility/OrderingTestRunner.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Utility/OrderingTestRunnerTest.java
An approach for addressing LEXEVS-1839 - introducing a custom JUnit test runner to enforce ordering of test execution. This can be done explicitly by annotating the tests with an @Order annotation and running the class with the custom test runner.
This prevents the need to refactor test cases, as well as only requires change to tests that are order dependent (which should be the minority of tests).
> LEXEVS-1839 - introduce a custom JUnit test runner to enforce test order.

- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Utility/OrderingTestRunnerTest.java
An approach for addressing LEXEVS-1839 (take 2) - introducing a custom JUnit test runner to enforce ordering of test execution. This can be done explicitly by annotating the tests with an @Order annotation and running the class with the custom test runner.
This prevents the need to refactor test cases, as well as only requires change to tests that are order dependent (which should be the minority of tests).
> An approach for addressing LEXEVS-1839 (take 2).

- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/function/TestUtil.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/function/history/TestProductionTags.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java
- lbTest/src/test/java/org/lexevs/dao/index/operation/DefaultLexEVSIndexOperationsCleanupIndexesTest.java
- lbTest/src/test/java/org/lexevs/dao/index/operation/DefaultLexEVSIndexOperationsCreateIndexTest.java
- lbTest/src/test/java/org/lexevs/dao/index/operation/DefaultLexEVSIndexOperationsCreateMultipleIndexesTest.java
- lbTest/src/test/java/org/lexevs/dao/index/operation/DefaultLexEVSIndexOperationsRemoveTest.java
- lbTest/src/test/java/org/lexevs/dao/index/operation/DefaultLexEVSIndexOperationsWriteOverIndexTest.java
- lbTest/src/test/java/org/lexevs/dao/index/operation/SameSessionLoadandQueryTest.java
- lexevs-dao/src/main/java/org/lexevs/dao/index/operation/DefaultLexEvsIndexOperations.java
Test org.lexevs.dao.index.operation.DefaultLexEVSIndexOperationsCleanupIndexesTest.testMultipleIndexCreation is still failing on the CI server, but I'm fairly certain that there is no ordering problem within the test itself. That issue may need to be explored further, independently.
> Some more ordering changes for LEXEVS-1839.

- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/bugs/GForge19650.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/function/TestUtil.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/function/history/TestProductionTags.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/LoadTestDataTest.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Utility/OrderingTestRunner.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Utility/OrderingTestRunnerTest.java
- lbTest/src/test/java/org/LexGrid/valueset/test/LoadTestDataTest.java
- lbTest/src/test/java/org/LexGrid/valueset/test/PickListAllTests.java
- lbTest/src/test/java/org/LexGrid/valueset/test/VDAllTests.java
- lbTest/src/test/java/org/lexevs/dao/index/operation/DefaultLexEVSIndexOperationsCleanupIndexesTest.java
- lbTest/src/test/java/org/lexevs/dao/index/operation/DefaultLexEVSIndexOperationsCreateIndexTest.java
- lbTest/src/test/java/org/lexevs/dao/index/operation/DefaultLexEVSIndexOperationsCreateMultipleIndexesTest.java
- lbTest/src/test/java/org/lexevs/dao/index/operation/DefaultLexEVSIndexOperationsRemoveTest.java
- lbTest/src/test/java/org/lexevs/dao/index/operation/DefaultLexEVSIndexOperationsWriteOverIndexTest.java
- lbTest/src/test/java/org/lexevs/dao/index/operation/SameSessionLoadandQueryTest.java
- lexevs-dao/src/main/java/org/lexevs/dao/index/operation/DefaultLexEvsIndexOperations.java
Fix for LEXEVS-1880 - index cleanup routines were returning early and skipping a step to sync with the index metadata registry. If the metadata index was found in ```org.lexevs.dao.index.operation.DefaultLexEvsIndexOperations#cleanUp```, it was exiting the method. This short-circuited cleanup for any indexes after this. So, cleanup was dependent on when the metadata index was processed -- which in turn was dependent on in which order the directories were read from the file system.
>  Fix for LEXEVS-1880 - index cleanup routines were returning early.

- lexevs-dao/src/main/java/org/lexevs/dao/index/operation/DefaultLexEvsIndexOperations.java
Fix for LEXEVS-1880 - index cleanup routines were returning early and skipping a step to sync with the index metadata registry. If the metadata index was found in org.lexevs.dao.index.operation.DefaultLexEvsIndexOperations#cleanUp, it was exiting the method. This short-circuited cleanup for any indexes after this. So, cleanup was dependent on when the metadata index was processed -- which in turn was dependent on in which order the directories were read from the file system.
> Fix for LEXEVS-1880 - index cleanup routines were returning early.

- lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/NewOWL2SnippetTestIT.java
- lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/AssociationWrapper.java
- lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java
LEXEVS-2801 Updated AssociationWrapper to set the entityDescription as the formal name.   This is for Annotations As Association. (6.4.0 branch)
> bugfix/LEXEVS-2801 Updated AssociationWrapper to set the entityDescription as the formal name (6.4.0 branch).

- lbTest/resources/testData/owl2/catalog-v001.xml
- lbTest/resources/testData/owl2/owl2-special-cases-Defined-Annotated.owl
- lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/NewOWL2SnippetTestIT.java
- lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/OWL2SpecialCaseSnippetTestIT.java
- lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/AssociationWrapper.java
- lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java
OWL2 loads of OWL2 source no longer reference complex properties to define attributes such as source for definitions.  This remedies some of the source related failings of the OWL2 loader.
> Bugfix/lexevs 2802  OWL2 Loader updated to reference complex property style annotation properties

- lbImpl/src/org/LexGrid/LexBIG/Impl/loaders/BaseLoader.java
This had a somewhat narrow implementation. Occasionally it created silent fails, so we added conditional messaging depending on the state of the stack trace.
> LEXEVS-2849. Updates to logging and error output on the BaseLoader class

- lbImpl/src/org/LexGrid/LexBIG/Impl/namespace/DefaultNamespaceHandler.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/namespace/DefaultNamespaceHandlerTest.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java
This is a fairly narrow use case that only occurs when querying on non production terminologies that have a different namespace applied to the entity than is the coding scheme name.  We've added some logic to remedy this.
> Bugfix/lexevs 2848 Query against non  production terminology using namespace fails

- lbImpl/src/org/LexGrid/LexBIG/Impl/helpers/lazyloading/AbstractLazyLoadableCodeToReturn.java
- lbImpl/src/org/LexGrid/LexBIG/Impl/namespace/DefaultNamespaceHandler.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/function/codednodeset/ResolveTest.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/helpers/lazyloading/LazyLoadableCodeToReturnTest.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/namespace/DefaultNamespaceHandlerTest.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java
This fixes an error traced back to a Unit test that did not use the correct naming convention and had it's own load of an index defined.  The error is corrected in the api and all instances of testing.
> Bugfix/lexevs 2855  EntityTypes not returned with coded node set query

- lbAdmin/scripts/RemoveResolvedValueSet.bat
- lbAdmin/scripts/RemoveResolvedValueSet.sh
- lbAdmin/scripts/RemoveVSResolvedFromCodingScheme.bat
- lbAdmin/scripts/RemoveVSResolvedFromCodingScheme.sh
- lbTest/src/test/java/org/LexGrid/valueset/impl/LexEVSResolvedValueSetTest.java
- lbTest/src/test/java/org/LexGrid/valueset/impl/LexEVSValueSetDefServicesImplTest.java
- lbTest/src/test/java/org/LexGrid/valueset/test/CleanUpTest.java
- lgValueSets/src/org/lexgrid/resolvedvalueset/impl/LexEVSResolvedValueSetServiceImpl.java
- lgValueSets/src/org/lexgrid/valuesets/admin/RemoveResolvedValueSet.java
- lgValueSets/src/org/lexgrid/valuesets/admin/RemoveVSResolvedFromCodingSchemes.java
- lgValueSets/src/org/lexgrid/valuesets/helper/VSDServiceHelper.java
We broke this tool, thinking it should do something else.  In the meantime other errors crept in that were not caught by current testing.  We should have full testing and correct code in place now.  We also have separated functionality into two classes so that the intent of both the original class and new implementation have been preserved.
> Bugfix/lexevs 2892 Reinstating and repairing some functionality to a Value Set removal tool

- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java
- lbTest/src/test/java/org/lexevs/dao/index/operation/OrphanedIndexTest.java
- lexevs-dao/src/main/java/org/lexevs/dao/index/lucenesupport/LazyLoadMetaData.java
- lexevs-dao/src/main/java/org/lexevs/system/constants/SystemVariables.java
- lexevs-dao/src/test/java/org/lexevs/dao/indexer/utility/LazyLoadMetaDataTest.java
This is a feature that some found too unforgiving when a poorly configured environment started up over imported indexes, LexEVS would delete them.
> Bugfix/lexevs 2896  Removing destructive Index management and replacing with exception

- lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/NewOWL2SnippetTestIT.java
- lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java
Fixes some bad formatting caused by the Manchester OWL rendering engine.
> LEXEVS-2994.  Anonymous node entityDescriptions contain return characters

- lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OWL2UnitTests.java
- lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java
A previous formatting fix and other Manchester OWL renderer conventions created extra white space between characters.  All extra white space is now removed.
> Bugfix/lexevs 3042 Removing extraneous white space from Manchester OWL formatting

- lbTest/resources/testData/Automobiles.xml
- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/function/query/TestHierarchyAPI.java
Lack of a supported association for one declared in the supported hierarchy caused method to fail.  No code fix needed, just better source configuration.
> Bugfix/lexevs 3092  Fix for source anomaly in Automobiles.xml

- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/MappingExtensionImplTest.java
- lexevs-dao/src/main/resources/ibatis/v20/entityAssnsToEntity.xml
This now pulls the namespace from the target scheme.  Update to the query is minimal, testing is a couple of additional assertions.
> LEXEVS-3748.  Update Mapping Concept Reference Namespace Implementation

- lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/assertedValueSets/EntityToVSDTransFormerTest.java
- lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/assertedValueSets/EntityToVSDTransformer.java
This happens when an equivalent coding scheme was not properly defined
> LEXEVS-4056. Committing a fix for mappings in asserted value set tranformations

- lbAdmin/scripts/RemoveAllValueSetDefinitions.bat
- lbAdmin/scripts/RemoveAllValueSetDefinitions.sh
- lgValueSets/src/org/lexgrid/valuesets/admin/RemoveAllValueSetDefinitions.java
LEXEVS-4086 added option (-f) to force the value set definition removal.
> LEXEVS-4086 added option (-f) to force the value set definition removal.

- lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/OWL2SpecialCaseSnippetTestIT.java
- lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java
LEXEVS-2020 Updated OWL2 loader to default the presentation property isPreferred value to false, if it wasn't set.
> LEXEVS-2020 Updated OWL2 loader to default the presentation property isPreferred value to false, if it wasn't set.

- lbAdmin/scripts/SourceAssertedValueSetDefinitionLoad.sh
Bugfix/lexevs 3877 Documentation: Script SourceAssertedValueSetDefinitionLoad.sh example is not correct
> Bugfix/lexevs 3877 Documentation: Script SourceAssertedValueSetDefinitionLoad.sh example is not correct

- lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/assertedValueSets/SourceAssertedValueSetSearchIndexServiceTest.java
- lbTest/src/test/java/org/lexevs/dao/index/operation/SourceAssertedVSLoadTest.java
- lgValueSets/src/org/lexgrid/valuesets/sourceasserted/impl/SourceAssertedValueSetServiceImpl.java
Bugfix/lexevs 4427 Update getSourceAssertedValueSetForValueSetURI() to return the correct coding scheme when there are multiple to choose from.
> Bugfix/lexevs 4427 Update getSourceAssertedValueSetForValueSetURI() to return the correct coding scheme when there are multiple to choose from.

- lbImpl/src/org/LexGrid/LexBIG/Impl/Extensions/tree/service/PathToRootTreeServiceImpl.java
- lbPackager/build.properties
- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/Extensions/tree/test/TestGetTree.java
Fixes an issue where empty and other poorly defined hierarchies break the tree extension resolution functions.
> Bugfix/lexevs 4535  Correcting a Hierarchy implementation issue for Tree Extension

- lbTest/resources/[lbImpl] All Tests - NormalConfig.launch
- lbTest/resources/testData/owl2/owl2-special-cases-Defined-Annotated.owl
- lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/owl2/OWL2SpecialCaseSnippetTestIT.java
- lgConverter/src/edu/mayo/informatics/lexgrid/convert/directConversions/owlapi/OwlApi2LG.java
This corrects an issue created by the OWL API where it doesn't recognize the numeric remainder.
> LEXEVS-4607. OWL API bug requires adaptation for numeric IRI remainder.

- lbImpl/src/org/LexGrid/LexBIG/Impl/dataAccess/RestrictionImplementations.java
- lbTest/resources/testData/owl2/owl2-special-cases-Defined-Annotated.owl
- lbTest/src/test/java/edu/mayo/informatics/lexgrid/convert/directConversions/graphdb/TestGraphQueryMethodsTestData.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/function/query/TestUntokenizedQualifierForSourceCode.java
- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/testUtility/AllTestsNormalConfig.java
- lexevs-dao/src/main/java/org/lexevs/dao/index/indexer/LuceneLoaderCode.java
source-code qualifier named qualifiers are broken out of the indexed qualifier list and redone with a seperate set of fields.
> LEXEVS-4768.  Allowing queries against an untokenized, source-code named, qualifier

- lbPackager/build.properties
Bugfix/lexevs 4812 - updated version for buidling snapshot.
> LEXEVS-4812 - updated version for buidling snapshot

- lbTest/src/test/java/org/LexGrid/LexBIG/Impl/Extensions/GenericExtensions/MappingExtensionImplTest.java
These should not be run in the remote api anyway.
> LEXEVS-4822.  Annotating some tests to remove from distributed testing

- lbPackager/build.properties
LEXEVS-4896 Updated version for snapshot 131.
> LEXEVS-4896 Updated version for snapshot 131.
